pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven { url = 'https://maven.parchmentmc.org' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.5.0'
}

rootProject.name = 'just-enough-accidents-forge-1.20'

def mineBackupDir = providers.gradleProperty('minebackupDir')
        .getOrElse('../../../Forge/Forge-1.20')

includeBuild(mineBackupDir) {
    name = 'minebackup-forge-1.20'
    dependencySubstitution {
        substitute module('com.leafuke.minebackup:minebackup') using project(':')
    }
}
